### ISSUE TITLE
TypeScript type for children is missing a render function

### ISSUE THREAD

**Issue by thitemple** [AlexGilleran/jsx-control-statements#107]
Hi this is adding a type for TChildren that allows components with children with render functions, without this, we have a TS error for the following:

```ts
function Component() {
  return (
     <SomeOtherComponent>
      {(props) => (<div>{props.something}</div>)}
     </SomeOtherComponent>
  )
}
```

I have sent a [PR for this already](https://github.com/AlexGilleran/jsx-control-statements/pull/106), it's just missing one line

**Comment by AlexGilleran** [comment]
Resolved in #106
