### ISSUE TITLE
Problem with ./node_modules/tsx-control-statements/components.ts

### ISSUE THREAD

**Issue by HugoFortunato** [AlexGilleran/jsx-control-statements#114]
## Problem

Basically I get this message when implementing some lib component, for example For .

![image](https://user-images.githubusercontent.com/67443788/172712047-4a2b5f0e-b214-47b4-9084-d504aa2effa3.png)

I'm using nextjs.

I used this for installation in tsx:

`yarn add tsx-control-statements` (https://www.npmjs.com/package/tsx-control-statements)

`yarn add --save-dev babel-plugin-jsx-control-statements`

babel file:

```
{
  "presets": ["next/babel", "@babel/preset-typescript"],
  "plugins": [
    [
      "babel-plugin-styled-components",
      {
        "ssr": true,
        "displayName": true
      }
    ]
  ],
  "env": {
    "test": {
      "plugins": [
        [
          "babel-plugin-styled-components",
          {
            "ssr": false,
            "displayName": false
          }
        ],
        ["jsx-control-statements"],
        ["transform-react-inline-elements"]
      ]
    }
  }
}
```

**Comment by AlexGilleran** [comment]
Looks like you're using [tsx-control-statements](https://github.com/KonstantinSimeonov/tsx-control-statements) and importing one of those directly? e.g. `import { For } from 'tsx-control-statements/components';` ?

I'm pretty sure you don't need to import this at all if you're using tsx-control-statements, it's completely stand-alone from jsx-control-statements. You'll need to override the next.js webpack config to include the tsx-control-statements stuff - it's not my repo so I don't know too much about how it works but I believe there's a webpack config example that you could adapt [here](https://github.com/KonstantinSimeonov/tsx-control-statements/tree/f2dcdf6166c9169bd958de0570e3da081a9b4608/examples/webpack).

**Comment by HugoFortunato** [comment]
@AlexGilleran Yes! I'm using `import { For } from 'tsx-control-statements/components';`

Please, tell me more about how I can override the next.js webpack. I saw the example repo, but I'm not seeing things in common for adapt.

Can you help me?

**Comment by KonstantinSimeonov** [comment]
For visibility: `jsx-control-statements` and `tsx-control-statements` are different packages. To use with `Tsx-control-statements` with `webpack`, one needs to use `ts-loader` or another typescript loader. Also `tsx-control-statements` probably won't work with the babel preset for typescript, since that outsources the transpilation to babel. Seems like `jsx-control-statements` now provides typings so folks should just stick to it when using babel.

@AlexGilleran I believe you can close this issue :v:
