### ISSUE TITLE
Make jsx-control-statements work with babel-6

### ISSUE THREAD

**Issue by tikiatua** [AlexGilleran/jsx-control-statements#13]
Hi there,

I just love this package. It really improves readability of the jsx code when using control statements. However, the package does not seem to work anymore with babel-6. 

Probably due to the babel.Transformer not being present any more. I will try to take a shot at fixing it. Any help would be greatly appreciated.

**Comment by AlexGilleran** [comment]
Ah nuts, thanks for calling it out. I'll take a look too :)

**Comment by tikiatua** [comment]
Thanks. Apparently there is not much documentation yet available on how to write plugins for babel-6 (see slack-channel for babeljs/plugins for more information). It does seem like all plugins use a visitor property to transform code.

**Comment by AlexGilleran** [comment]
So I've had a look at it - I can change to the new API within the visitors pretty easily, but I've got no idea how to make the plugin run before the other React plugins while still having them run... as much as I love Babel I'm not super impressed at them changing all this and not documenting any of it - I guess the fix will have to wait until they've actually written some documentation.

**Comment by AlexGilleran** [comment]
OK so turns out there isn't really that much need for major surgery (got a bit confused by something caching the output of jsx require calls, meaning that even if I changed the transformer it didn't get called until I bumped the last modification of the jsx file).

... unfortunately there's now an extra bit of validation that prevents me from implementing it the same way, so I've raised a bug (babel/babel#3038) and hopefully I've either figured out the API wrong or we can get that fixed.

**Comment by AlexGilleran** [comment]
Well, that wasn't super polite but it turns out I was using the API wrong, all unit tests are now passing.

Will publish to NPM when I can test it on an actual project... unfortunately this is blocked by other Babel bugs atm.

**Comment by AlexGilleran** [comment]
Finally finished testing it in anger, fix is live as v2.0.0 :)

**Comment by tikiatua** [comment]
Thank you very much. Might finally be able to switch to babel6. Did you find any documentation on how to write babel plugins (website still seems to be very sparse about that).

**Comment by AlexGilleran** [comment]
No :(. Mainly got by by reading the existing JSX plugins and copying them - might write a blog post or something about it later.
