### ISSUE TITLE
The plugin "jsx-control-statements/babel" didn't export a Plugin instance

### ISSUE THREAD

**Issue by tomitrescak** [AlexGilleran/jsx-control-statements#14]
Hi

Thanks for this nice solution! It really helps to clear up the code.
I have a bit problem though when deploying the solution with CI which fails on the following message:

`The plugin "jsx-control-statements/babel" didn't export a Plugin instance`

My config is following:

```
var babelSettings = {
  stage: 0,
  plugins: ['jsx-control-statements/babel']
};

module.exports = {
  entry: './entry',
  module: {
    loaders: [
      { test: /\.tsx?$/, loader: 'babel?' + JSON.stringify(babelSettings) + '!awesome-typescript', exclude: /node_modules|lib/ },
      { test: /\.jsx?$/, loader: 'babel', query: babelSettings, exclude: /node_modules/ },
      { test: /\.css$/, loader: 'style!css' },
      { test: /\.(png|jpe?g)(\?.*)?$/, loader: 'url?limit=8182' },
      { test: /\.(svg|ttf|woff|woff2|eot)(\?.*)?$/, loader: 'file' }
    ]
  }
};
```

Any idea what can be wrong? Thanks!

**Comment by AlexGilleran** [comment]
Looks like you're using jsx-control-statements 2.0 with Babel 5... because Babel 6 has breaking changes to the plugin API, JCS 2.0 only works with the new version. So either going back to JCS 1.x or upgrading Babel to 6 should fix it :).

Apologies, this really should be made clear in the Readme - I'll try to fix that up a bit later.

**Comment by AlexGilleran** [comment]
Updated the readme to make this clearer - please comment if that didn't fix the problem, otherwise I'll close this issue :).

**Comment by tomitrescak** [comment]
Thanks for the clarification, certainly will help ;) As for me, I moved the solution to Webpack chaining and it solved it for me.
