### ISSUE TITLE
Drop support for jstransform?

### ISSUE THREAD

**Issue by texttechne** [AlexGilleran/jsx-control-statements#21]
Since jstransform is no longer actively maintained, do you plan to drop support for it?
Would be much easier to maintain and extend.

**Comment by AlexGilleran** [comment]
Huh didn't actually realise they'd stopped supporting it, the npm page still has the old readme.

Yeah it definitely sucks doing everything twice - I think the best course of action would be another major version for jsx-control-statements that continues with the Babel plugin, and JSTransform split off into another repo that can be forked if needed by anyone still using JCS through JSTransform (which surely can't be that many people given that it's such an annoyance to configure).

**Comment by texttechne** [comment]
Your upgrade plan sounds good. 

I have another PR for issue #16 to support the following cases:
```
<If condition={foo}>
  {'foo'}
</If>

<If condition={foo}>
  foo
</If>
```

It's currently sitting in my master branch, but only works for babel. No idea and no enthusiasm to dig into jstransform to realise it there...

**Comment by AlexGilleran** [comment]
Ah awesome! Fair enough then - will do the split ASAP.

**Comment by AlexGilleran** [comment]
Have created a separate JSTransform repo [Here](https://github.com/AlexGilleran/jsx-control-statements-jstransform), will shortly remove JSTransform out of this one and publish both to NPM as 3.0.0

**Comment by AlexGilleran** [comment]
Done in 3.0.0
