### ISSUE TITLE
Allow for more than one child

### ISSUE THREAD

**Issue by texttechne** [AlexGilleran/jsx-control-statements#23]
Currently it is more a technical than a semantic restriction to allow only one child element within control statements.

We could give up error checking: 
```
if (ifBlock.length > 1) {
  throwError(errors.MULTIPLE_CHILDREN, node, file);
} else if (ifBlock.length === 0) {
  throwError(errors.NO_CHILDREN, node, file);
} else {
  ifBlock = ifBlock[0];
}
```
Instead something along this lines could work:
```
ifBlock = ifBlock.length > 1 ?  t.ArrayExpression(ifBlock) : ifBlock[0];
```
Consequences: 
* In contrast to single elements sometimes additional `<span>`s are created, but that is how React works
* `key`s are required: should they be injected into each element automatically or left to the user (quite unintuitive)?

**Comment by AlexGilleran** [comment]
Previous discussion: https://github.com/AlexGilleran/jsx-control-statements/issues/2

It got closed before because I wanted to keep the whole thing small, but it's coming up a lot so definitely happy to revisit it - we just have to come up with a good solution re: key generation.

**Comment by texttechne** [comment]
Closing in favour of #2
