### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by texttechne** [AlexGilleran/jsx-control-statements#30]
First of all, since this release would only add new features, but doesn't break anything, I think it should be release version 3.1.0.

Todos
- [x] Fix #2
- [x] Documentation of `<Choose>`
- [x] Documentation of multiple elements and caveats
- [x] Create issues for ESLint-Plugin
- [x] Remove lodash

I think, we should ship 3.1.0 when the ESLint-Plugin is ready.

**Comment by texttechne** [comment]
ESLint Issues:
- vkbansal/eslint-plugin-jsx-control-statements/issues/3
- vkbansal/eslint-plugin-jsx-control-statements/issues/4

**Comment by AlexGilleran** [comment]
Do you have an npm account I can add to the npm module?

**Comment by texttechne** [comment]
nope, not yet. I hoped you would take over from here :-)

**Comment by AlexGilleran** [comment]
Heh ok no worries. Probably won't have time to go at your pace though ;).

**Comment by texttechne** [comment]
Added some documentation for <Choose> and multiple children.

**Comment by AlexGilleran** [comment]
Nice work getting all this done, apologies I haven't had much time to contribute :).

**Comment by texttechne** [comment]
You're welcome and there are no apologies needed.

Would love to see this released. Especially since the documentation is now out of sync with the released stuff... I mean the documentation could be improved, but that is not dependent on the release. Also the ESLintPlugin is not quite ready, but let's get this out of the door. Then we should add some linting to the project to easily verify that it is working as expected.

**Comment by AlexGilleran** [comment]
[Released as v3.1.0 :)](https://github.com/AlexGilleran/jsx-control-statements/releases/tag/v3.1.0)
