### ISSUE TITLE
Remove usage of lodash

### ISSUE THREAD

**Issue by Daniel15** [AlexGilleran/jsx-control-statements#33]
Lodash is only used a few times, and all the usages seem to be pretty simple use cases that could be replaced with native functions like Array.prototype.reduce and Array.prototype.forEach. There's no point adding the weight of the entire lodash library :)

**Comment by AlexGilleran** [comment]
Is the weight of it that much of a problem? Keep in mind that the libraries included in JSX Control Statements don't actually get included in your app, so this will only affect the initial `npm install`.

**Comment by Daniel15** [comment]
Someone was requesting instructions on how to use it with [babel-standalone](https://github.com/Daniel15/babel-standalone), which is a standalone build of Babel for use in non-Node.js environments (including browsers). If they wanted to use it in a client-side script for whatever reason (eg. a REPL, or site like JSBin/JSFiddle), it would require bundling lodash too, adding unnecessary weight :smiley: 

IMO lodash isn't as useful as it once was, now that arrays have a bunch of functional methods on them, and using `Object.keys` + the array methods tends to solve a lot of the use-cases for objects.

**Comment by AlexGilleran** [comment]
Ah yeah that makes sense, will look into it :).

**Comment by texttechne** [comment]
Fixed in master.

Used lodash methods:
* forEach / forEachRight
* reduce / reduceRight
* template

Only challenge was to replace the last method. Should be included in release 3.1.0.

**Comment by Daniel15** [comment]
Nice! :)

**Comment by AlexGilleran** [comment]
Done in v3.1.0
