### ISSUE TITLE
For statement and if statement without curly braces

### ISSUE THREAD

**Issue by tomitrescak** [AlexGilleran/jsx-control-statements#34]
Hi, would you consider adding a flag, in which you specify, whether curly brackets should be rendered or not? Consider this situation:

```
<For each="item" index="index" of={this.props.visibleItems}>
      { this.renderPracticalItem(Collections.Practicals.findOne(item.practicalId), this.props.schedule._id) }
</For>
```

In the for loop I need to render elements in which I do not want to render a containing element. The way to do it now is a bit hacky:

```
<For each="item" index="index" of={this.props.visibleItems}>
      this.renderPracticalItem(Collections.Practicals.findOne(item.practicalId), this.props.schedule._id)
</For>
```

**Comment by AlexGilleran** [comment]
So you're seeing the curly brackets rendered in the first example?

**Comment by tomitrescak** [comment]
In the first example it will fail in the broser with the error as two curly braces are rendered.

**Comment by jimfb** [comment]
@tomitrescak What version of jsx-control-statements are you on?

When I run against the latest npm release, I get exactly the results I would expect: http://jsfiddle.net/z3b1b2ea/

**Comment by tomitrescak** [comment]
I'm on version two, as the meteor Webpack does not play well with Babel plugins so am using jsx transform way. But I'll check if things have changed and upgrade to version three. I'll post back

**Comment by tomitrescak** [comment]
Upgrading to version 3 solve the issue. Thanks.
