### ISSUE TITLE
Choose statement not working in Typescript

### ISSUE THREAD

**Issue by tomitrescak** [AlexGilleran/jsx-control-statements#35]
Thanks you or this amazing set of controls that improve the readability of the code. Yet, I have a bit issue since I am a Typescript developer and I cannot make the choose statement to work, since it does not belong to the basic set of jsx statements. The If and For were no issue, since they are in capitals, thus only custom functions. What is the reason behind having "choose" and "when" with small letters? Would it be possible to use both, "Choose" and "choose"? Thanks!

**Comment by AlexGilleran** [comment]
So it's not working if you capitalise them? In our tests `Choose` and `When` are in capitals:

https://github.com/AlexGilleran/jsx-control-statements/blob/master/spec/fixtures/choose/choose.jsx

**Comment by AlexGilleran** [comment]
Or am I getting this back to front and you actually need this in small letters instead of Big Ones?

**Comment by tomitrescak** [comment]
Alex, let me test it and get back to you. On the first try it threw errors yesterday, maybe something with Typescript compiler. Lemme check that.

**Comment by AlexGilleran** [comment]
No worries :). If you get it working I'd love to hear how you configured jsx-control-statements to work with Typescript, I've been wondering about that myself lately.

**Comment by tomitrescak** [comment]
Alex, all good. It works, not sure why it didn't in the first place.

To make stuff work, all you need to do is to add following typings and reference them in your `tsconfig.json` file:

```typescript
declare function If (condition: any): any;
declare function For(each: string, index: string, of: any): any;
declare var Else: any;
declare var Choose: any;
declare function When (condition: any): any;
```
