### ISSUE TITLE
Can this be done with vanilla React?

### ISSUE THREAD

**Issue by trusktr** [AlexGilleran/jsx-control-statements#36]
Maybe it's possible to create If, For, etc, components in React, without needing to extend JSX? Foe example,

```html
<For items={someArray}>
  <div>...</div>
</For>
```

Then the `For` component would see thie child, and clone it for each item passed in to the items prop. It'd work without JSX. I can imagine the code to make that happen.

What are the pros/cons of introducing a compile step versus runtime components?

**Comment by trusktr** [comment]
A compile-step advantage I see is being able to convert `each="item"` into a variable reference, not possible with runtime.

**Comment by texttechne** [comment]
Actually there are a couple of projects which realize the conditional part as React component. But their problem is also the main reason this project was started: Conditionals don't work as expected, as they get evaluated even if the condition is false. The following code wouldn't work:
```
<If condition={obj}>
    <div>{obj.name}<div>
  </If>
```
Hence the compilation step which is the only elegant way to solve this.

Read also [Why Transform](https://github.com/AlexGilleran/jsx-control-statements/wiki/Why-Transform). This reason should probably be made more prominent, like putting it into the intro section. So let's keep this issue open until it is better documented.

**Comment by texttechne** [comment]
### Pros
- Conditionals are not flawed
- For statements are made possible as component
- There's no penalty on the runtime performance
- It works exactly as JSX is supposed to work: Plain syntactic sugar

### Cons
- Requires Babel

**Comment by texttechne** [comment]
Closing in favor of #39
