### ISSUE TITLE
Should <Else /> be deprecated?

### ISSUE THREAD

**Issue by AlexGilleran** [AlexGilleran/jsx-control-statements#41]
It made sense to me at the very start when I was just writing this for me, but at this point I think it's outlived its welcome. It's bad JSX/XML semantics, it breaks auto-formatting and we have a much nicer construct for this kind of thing in Choose/Otherwise now.

We obviously should keep `If` because it's useful for single-branch conditionals - I'm thinking maybe just drop `Else` from the documentation as we redo it, making extra sure to point out that Choose/When/Otherwise is equivalent to If/Else with cleaner semantics.

**Comment by texttechne** [comment]
This definitely makes sense. 

I still want to implement `<If></If><Else></Else>` if I find the time. So deprecating `<Else/>` would be part of this change. Are you still willing to accept it?

**Comment by azz0r** [comment]
Having just implementing this into my project: no.

**Comment by AlexGilleran** [comment]
@azz0r: this isn't about removing `<Else />`, just deprecating it - it'd continue to work but we'd stop telling people to use it.

`<If></If><Else></Else>` would be cool but only if we can avoid breaking backwards compatibility - maybe by treating `<Else></Else>` and `<Else />` differently?

**Comment by texttechne** [comment]
@AlexGilleran I rewrote the API doc. I think it's good to still mention it and name the reasons why we`ve deprecated it, but removed any example of its usage.
