### ISSUE TITLE
React Native Compatibility

### ISSUE THREAD

**Issue by smooJitter** [AlexGilleran/jsx-control-statements#49]
Can you note compatibility with RN in the Repo write-up

**Comment by AlexGilleran** [comment]
I haven't tried it as I don't use React Native - but it's a pretty simple Babel plugin so you should be able to plug it into your React Native build as described here http://stackoverflow.com/questions/34301739/run-a-custom-babel-transform-with-react-native - does it work for you?

**Comment by texttechne** [comment]
Added a note on compatibility within the intro section.
