### ISSUE TITLE
Work with babel-plugin-transform-react-inline-elements?

### ISSUE THREAD

**Issue by navgarcha** [AlexGilleran/jsx-control-statements#55]
Is it possible to get this plugin to work alongside [babel-plugin-transform-react-inline-elements](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-inline-elements)?

**Comment by AlexGilleran** [comment]
I would think it should do - are you putting `jsx-control-statements` before `transform-react-inline-elements` in your babelrc? JSX Control Statements will have to run first.

**Comment by navgarcha** [comment]
`transform-react-inline-elements` is actually in my `env` specific part of my `.babelrc` and when this is merged in with the 'non-env' config it appears to place `transform-react-inline-elements` before `jsx-control-statements`. 

It's no neat but i've had todo the following to fix this:

```
{
    "presets": [
        // ...
    ],
    "plugins": [
        "add-module-exports",
        "react-require"
    ],
    "env": {
        "development": {
            "plugins": [
                "jsx-control-statements"
            ]
        },
        "production": {
            "plugins": [
                "jsx-control-statements",
                "babel-plugin-transform-react-inline-elements"
            ]
        }
    }
}
```

**Comment by AlexGilleran** [comment]
Thanks for sharing the solution! :)
