### ISSUE TITLE
Export dummy components for <If /> ... etc

### ISSUE THREAD

**Issue by gajus** [AlexGilleran/jsx-control-statements#62]
At the moment, I need to declare types as globals to use `jsx-control-statements`, e.g.

```js
declare var If: any;

```

Otherwise, I will get Flow/ESLint error that `If` variable is not defined.

Instead, it would be nice if I could simply import a dummy component from `jsx-control-statements`, e.g.

```js
import {If} from 'jsx-control-statements';

```

**Comment by AlexGilleran** [comment]
There are actually already FlowTypes [here](https://github.com/AlexGilleran/jsx-control-statements/blob/master/jsx-control-statements.flow.js).

The only problem is that I still can't think of a way to make it work for variables inside `For` :(.

For pure ESLint there's the excellent [JCS ESLint plugin](https://github.com/vkbansal/eslint-plugin-jsx-control-statements), which not only stops ESLint complaining about `<If>` but also treats `each="x"` variables as being actually declared.
