### ISSUE TITLE
[Suggestion] add prefix "babel-plugin-" to project name 

### ISSUE THREAD

**Issue by FourwingsY** [AlexGilleran/jsx-control-statements#70]
On Babel 7, plugins name on .babelrc became strict to single target: babel-plugin-{plugin-name}

```
{
  "plugins": [ ...
    "jsx-control-statements", // will find babel-plugin-jsx-control-statements only, and fails
    "module:jsx-control-statements", // will find jsx-control-statements correctly.
  ]
}
```

just adding installation manual for Babel 7 is simple solution,
but i think renaming jsx-control-statements to babel-plugin-jsx-control-statements is more better.
How do you think about it?

**Comment by AlexGilleran** [comment]
Yeah makes sense to me given that we've been just a babel plugin for some time 👍 .

**Comment by AlexGilleran** [comment]
Ok so given that no one objected I've:
- Created (babel-plugin-jsx-control-statements)[https://www.npmjs.com/package/babel-plugin-jsx-control-statements]
- Put a deprecation message on the old jsx-control-statements.
- Updated the `npm install` bit of the readme.

That should do it I think, thanks for the heads-up @FourwingsY 👍
