### ISSUE TITLE
Update to Babel 7

### ISSUE THREAD

**Issue by spoldman** [AlexGilleran/jsx-control-statements#80]
Now that Babel 7 is out I want to get rid of all references to Babel 6. This plugin is the only one that relies on that dependency in my current project. 
Happy to try to do a PR (not knowing how much work it would take)

**Comment by AlexGilleran** [comment]
Sounds reasonable to me, as long as we do a major version change for jsx-control-statements 👍

**Comment by spoldman** [comment]
I created a PR. https://github.com/AlexGilleran/jsx-control-statements/pull/81

**Comment by AlexGilleran** [comment]
Awesome! Will get to it soon :D

**Comment by AlexGilleran** [comment]
Merged, and published as 4.0.0 :+1: . Thanks!
