### ISSUE TITLE
Support babel-plugin-macros

### ISSUE THREAD

**Issue by kbzowski** [AlexGilleran/jsx-control-statements#82]
babel-plugin-macros are now enabled by default in react-scripts >= 2.
Could you add support for macros to jsx-control-statements?

**Comment by AlexGilleran** [comment]
Huh, if possible that would actually be really cool, I'll look into it.

**Comment by kbzowski** [comment]
I tried to make an attempt to implement such a macro for If
https://github.com/kbzowski/jsx-control-statements/commit/d4e4162c89d66696a699add7f736893278f64f38

This is my first meeting with Babel from the development side so there is still room for improvement. My test works, but I have no idea why mocha produces so many errors when I tried to run all tests together.

**Comment by viebel** [comment]
@AlexGilleran any update on this?

**Comment by AlexGilleran** [comment]
Ah yes, I remember saying I would do that and then never getting around to it, sorry about that.

I'm not going to be doing this because I don't want to be adding anything new to this repo (to be honest I don't really use it even for my own react projects), but if someone made a macro fork I'd be happy to link to it in the readme :)

**Comment by viebel** [comment]
@AlexGilleran What do you use for your own react projects for control statement components?

**Comment by AlexGilleran** [comment]
The main reason I made this in the first place was that doing control statements in react was really ugly. Since I started using prettier though, formatting the usual `{boolean && <Component />}` or `{boolean ? <Component /> : <OtherComponent />` style nice enough to be bearable, so I just do that.
