### ISSUE TITLE
last published version is 3 years old

### ISSUE THREAD

**Issue by igl** [AlexGilleran/jsx-control-statements#97]
I saw there were a few changes since. I am specially interested in the typescript definitions.
Is v4 intentionally hold back?

The latest version on the npm registry is:

`'3.2.8': '2017-10-02T11:17:35.445Z'`

**Comment by AlexGilleran** [comment]
You want https://www.npmjs.com/package/babel-plugin-jsx-control-statements. Had to add `babel-plugin` to the start to meet the new babel convention that came in.

**Comment by igl** [comment]
doh! ok
