### ISSUE TITLE
ESLint autofix

### ISSUE THREAD

**Issue by serhiipalash** [AlexGilleran/jsx-control-statements#98]
Hi! Thank you for such a great tool!

We have a huge codebase, is it possible to migrate the whole code on jsx-control-staements at once using some util or ESLint `--fix` option?

**Comment by AlexGilleran** [comment]
Hi @serhiipalash - it'd certainly be possible but I don't know of anything that already exists to do it :)

**Comment by serhiipalash** [comment]
@AlexGilleran I understand, thx
